credentials:
  usernames:
    alice:
      email: alice@example.com
      name: Alice
      password: $2b$12$9fTU/T1nD8nZ/bvttkoVnu6BcNsICMwIlCTOD2kbNkqxScbRgNljO  # use hashed passwords for real apps
    bob:
      email: bob@example.com
      name: Bob
      password: $2b$12$9fTU/T1nD8nZ/bvttkoVnu6BcNsICMwIlCTOD2kbNkqxScbRgNljO
