credentials:
  usernames:
    alice:
      email: alice@example.com
      name: Alice
      password: abc123  # use hashed passwords for real apps
    bob:
      email: bob@example.com
      name: Bob
      password: def456
